apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::334762911831:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
       - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::334762911831:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WBERWXJY5LMO
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-20T21:13:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2743"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5877d75e-b81c-4490-866d-384ab8ba843e
