apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::334762911831:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GB4YJU33N25D
      username: system:node:{{EC2PrivateDNSName}}
      
    - rolearn: arn:aws:iam::334762911831:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-13T20:57:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6717"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e5dd758c-06e5-4414-b21d-011cfbcbd448
